/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnimeButton {
    }
    interface AnimeNav {
    }
}
declare global {
    interface HTMLAnimeButtonElement extends Components.AnimeButton, HTMLStencilElement {
    }
    var HTMLAnimeButtonElement: {
        prototype: HTMLAnimeButtonElement;
        new (): HTMLAnimeButtonElement;
    };
    interface HTMLAnimeNavElement extends Components.AnimeNav, HTMLStencilElement {
    }
    var HTMLAnimeNavElement: {
        prototype: HTMLAnimeNavElement;
        new (): HTMLAnimeNavElement;
    };
    interface HTMLElementTagNameMap {
        "anime-button": HTMLAnimeButtonElement;
        "anime-nav": HTMLAnimeNavElement;
    }
}
declare namespace LocalJSX {
    interface AnimeButton {
    }
    interface AnimeNav {
    }
    interface IntrinsicElements {
        "anime-button": AnimeButton;
        "anime-nav": AnimeNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "anime-button": LocalJSX.AnimeButton & JSXBase.HTMLAttributes<HTMLAnimeButtonElement>;
            "anime-nav": LocalJSX.AnimeNav & JSXBase.HTMLAttributes<HTMLAnimeNavElement>;
        }
    }
}
